from __future__ import annotations

"""Toy data for MMRM.

This file generates a synthetic e-commerce search/ranking dataset with:

- query: token ids (simulating query text)
- item: (text token ids, image vector) per product
- user behavior history: a sequence of previously engaged item ids
- candidates: a fixed-size candidate set per query/session
- multi-task labels: click / purchase (purchase is a stricter positive)

The dataset is deliberately small and fully in-memory to keep the reproduction minimal.
"""

from dataclasses import dataclass
from typing import Dict, Tuple

import torch
from torch.utils.data import DataLoader, Dataset


@dataclass
class Catalog:
    """Product catalog holding multimodal features.

    Attributes:
        item_text_ids: (num_items, item_text_len) int64
        item_image: (num_items, image_dim) float32
    """

    item_text_ids: torch.Tensor
    item_image: torch.Tensor


class SearchRankingDataset(Dataset):
    """Synthetic sessions for search ranking."""

    def __init__(
        self,
        query_text_ids: torch.Tensor,
        history_item_ids: torch.Tensor,
        candidate_item_ids: torch.Tensor,
        click_labels: torch.Tensor,
        purchase_labels: torch.Tensor,
    ):
        self.query_text_ids = query_text_ids
        self.history_item_ids = history_item_ids
        self.candidate_item_ids = candidate_item_ids
        self.click_labels = click_labels
        self.purchase_labels = purchase_labels

    def __len__(self) -> int:
        return self.query_text_ids.size(0)

    def __getitem__(self, index: int) -> Dict[str, torch.Tensor]:
        return {
            "query_text_ids": self.query_text_ids[index],
            "history_item_ids": self.history_item_ids[index],
            "candidate_item_ids": self.candidate_item_ids[index],
            "click_labels": self.click_labels[index],
            "purchase_labels": self.purchase_labels[index],
        }


def _sample_token_ids(logits: torch.Tensor, length: int, generator: torch.Generator) -> torch.Tensor:
    """Sample `length` token ids from categorical distribution parameterized by logits.

    Args:
        logits: (vocab_size,)

    Returns:
        token_ids: (length,)
    """

    probs = torch.softmax(logits, dim=-1)
    return torch.multinomial(probs, num_samples=length, replacement=True, generator=generator)


def build_datasets(
    *,
    num_items: int = 256,
    num_sessions: int = 4096,
    vocab_size: int = 256,
    query_text_len: int = 6,
    item_text_len: int = 10,
    image_dim: int = 32,
    latent_dim: int = 16,
    history_len: int = 8,
    num_candidates: int = 20,
    train_ratio: float = 0.8,
    seed: int = 7,
) -> Tuple[Catalog, SearchRankingDataset, SearchRankingDataset]:
    """Create a toy e-commerce search dataset.

    Notes on the data generating process:
    - Each item has a latent semantic vector z_i.
    - Query and user also have latent vectors; user history is sampled from user preference.
    - click/purchase labels are generated by thresholds on a noisy relevance score.

    This is *not* intended to reproduce real industrial data, only to provide a learnable
    signal for verifying the MMRM-shaped model.
    """

    g = torch.Generator().manual_seed(seed)

    # ----- world parameters -----
    item_latent = torch.randn(num_items, latent_dim, generator=g)
    vocab_proj = torch.randn(vocab_size, latent_dim, generator=g) * 0.7
    image_proj = torch.randn(image_dim, latent_dim, generator=g) * 0.6

    # ----- build catalog -----
    item_text_ids = []
    for i in range(num_items):
        logits = vocab_proj @ item_latent[i]
        item_text_ids.append(_sample_token_ids(logits, item_text_len, g))
    item_text_ids = torch.stack(item_text_ids, dim=0).to(torch.long)

    item_image = (item_latent @ image_proj.t()) + 0.05 * torch.randn(num_items, image_dim, generator=g)
    item_image = item_image.to(torch.float32)

    catalog = Catalog(item_text_ids=item_text_ids, item_image=item_image)

    # ----- generate sessions -----
    queries = torch.empty(num_sessions, query_text_len, dtype=torch.long)
    histories = torch.empty(num_sessions, history_len, dtype=torch.long)
    candidates = torch.empty(num_sessions, num_candidates, dtype=torch.long)
    click = torch.empty(num_sessions, num_candidates, dtype=torch.float32)
    purchase = torch.empty(num_sessions, num_candidates, dtype=torch.float32)

    temp = 0.6
    for s in range(num_sessions):
        user_latent = torch.randn(latent_dim, generator=g)
        query_latent = user_latent + 0.35 * torch.randn(latent_dim, generator=g)

        # history sampled from user preference over items
        hist_scores = (item_latent @ user_latent) / temp
        hist_probs = torch.softmax(hist_scores, dim=0)
        hist_ids = torch.multinomial(hist_probs, num_samples=history_len, replacement=True, generator=g)

        # candidates: 1 hard positive (top relevance) + random negatives
        relevance_for_sampling = (item_latent @ query_latent) + 0.4 * (item_latent @ user_latent)
        positive_id = int(torch.argmax(relevance_for_sampling).item())

        # avoid sampling the positive repeatedly for negatives
        neg_pool = torch.ones(num_items, dtype=torch.float32)
        neg_pool[positive_id] = 0.0
        neg_probs = neg_pool / neg_pool.sum()
        neg_ids = torch.multinomial(neg_probs, num_samples=num_candidates - 1, replacement=False, generator=g)

        cand_ids = torch.cat([torch.tensor([positive_id], dtype=torch.long), neg_ids.to(torch.long)], dim=0)
        perm = torch.randperm(num_candidates, generator=g)
        cand_ids = cand_ids[perm]

        # query text tokens
        q_logits = vocab_proj @ query_latent
        q_text = _sample_token_ids(q_logits, query_text_len, g).to(torch.long)

        # labels from noisy relevance
        z_cand = item_latent[cand_ids]
        rel = 0.20 * (z_cand * query_latent).sum(dim=-1) + 0.10 * (z_cand * user_latent).sum(dim=-1)
        rel = rel + 0.10 * torch.randn(rel.shape, generator=g)

        click_labels = (rel > 0.05).to(torch.float32)
        purchase_labels = (rel > 0.90).to(torch.float32)
        purchase_labels = torch.minimum(purchase_labels, click_labels)  # purchase implies click

        queries[s] = q_text
        histories[s] = hist_ids
        candidates[s] = cand_ids
        click[s] = click_labels
        purchase[s] = purchase_labels

    split = int(num_sessions * train_ratio)
    train_set = SearchRankingDataset(
        query_text_ids=queries[:split],
        history_item_ids=histories[:split],
        candidate_item_ids=candidates[:split],
        click_labels=click[:split],
        purchase_labels=purchase[:split],
    )
    test_set = SearchRankingDataset(
        query_text_ids=queries[split:],
        history_item_ids=histories[split:],
        candidate_item_ids=candidates[split:],
        click_labels=click[split:],
        purchase_labels=purchase[split:],
    )
    return catalog, train_set, test_set


def create_dataloaders(
    *,
    batch_size: int = 64,
    seed: int = 7,
    num_candidates: int = 20,
) -> Tuple[Catalog, DataLoader, DataLoader]:
    catalog, train_set, test_set = build_datasets(seed=seed, num_candidates=num_candidates)
    return (
        catalog,
        DataLoader(train_set, batch_size=batch_size, shuffle=True),
        DataLoader(test_set, batch_size=batch_size, shuffle=False),
    )
