"""
Tripartite Framework for Multimodal LLM-Based Multimedia Understanding
in Large-Scale Recommendation Systems.

Paper: arXiv:2605.09338 (SIGIR 2026)
Authors: Yiming Zhu, Xu Liu, et al. (Meta Platforms)

The three pillars:
1. Content Interpretation: LLaMA2-based model generates descriptive captions
   from multimedia content (images, video keyframes, audio)
2. Representation Extraction: Fuses captions + visual features into a unified
   semantic embedding
3. Pipeline Integration: Offline pre-computation + online serving at scale

Industrial key design decisions:
  - Offline caption generation to avoid latency at serving time
  - Frozen vision encoder + fine-tuned language model for caption quality
  - Semantic embedding used in existing Two-Tower or candidate retrieval pipeline
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Optional, List, Tuple, Dict
from dataclasses import dataclass


@dataclass
class ItemFeatures:
    """Multimodal features for a single item (product/video/post)."""
    item_id: str
    image_features: Optional[torch.Tensor]   # (visual_dim,)
    text_features: Optional[torch.Tensor]    # (text_dim,)
    audio_features: Optional[torch.Tensor]   # (audio_dim,) — optional
    caption: Optional[str] = None            # Generated by content interpreter


# ─── Pillar 1: Content Interpretation ─────────────────────────────────────────

class ContentInterpreter(nn.Module):
    """
    LLaMA2-based multimodal content interpreter.

    Given image/video visual features, generates descriptive caption text.
    The caption bridges the visual modality gap with text-based recommendation.

    In production: uses full LLaMA2 7B with visual adapter.
    Here: lightweight MLP decoder for reproducibility.

    Caption template (from paper):
      "This {item_type} shows {visual_description}. The main {attribute} is {value}."
    """

    def __init__(
        self,
        visual_dim: int = 2048,    # e.g., ResNet-50 or ViT-L output dim
        caption_vocab_size: int = 32000,  # LLaMA2 vocab
        d_model: int = 512,
        max_caption_len: int = 64,
        num_decoder_layers: int = 4,
        nhead: int = 8,
    ):
        super().__init__()
        self.d_model = d_model
        self.max_caption_len = max_caption_len

        # Visual feature projection
        self.visual_proj = nn.Sequential(
            nn.Linear(visual_dim, d_model),
            nn.LayerNorm(d_model),
            nn.GELU(),
        )

        # Caption token embedding
        self.token_embed = nn.Embedding(caption_vocab_size, d_model)
        self.pos_embed = nn.Embedding(max_caption_len + 1, d_model)

        # Cross-attention decoder (visual → caption)
        decoder_layer = nn.TransformerDecoderLayer(
            d_model=d_model, nhead=nhead, batch_first=True
        )
        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_decoder_layers)
        self.output_proj = nn.Linear(d_model, caption_vocab_size)

    def forward(
        self,
        visual_features: torch.Tensor,  # (B, visual_dim) or (B, T, visual_dim)
        caption_ids: Optional[torch.Tensor] = None,  # (B, L) for training
    ) -> torch.Tensor:
        """
        Returns:
          Training mode (caption_ids provided): logits (B, L, vocab_size)
          Inference mode: generated caption ids (B, max_len)
        """
        B = visual_features.shape[0]

        # Handle both image (2D) and video (3D) features
        if visual_features.ndim == 2:
            visual_features = visual_features.unsqueeze(1)  # (B, 1, visual_dim)

        # Project visual features
        memory = self.visual_proj(visual_features)  # (B, T_v, d_model)

        if caption_ids is not None:
            # Training: teacher-forced decoding
            L = caption_ids.shape[1]
            token_emb = self.token_embed(caption_ids)  # (B, L, d_model)
            pos_ids = torch.arange(L, device=caption_ids.device)
            token_emb = token_emb + self.pos_embed(pos_ids)

            causal_mask = torch.triu(
                torch.ones(L, L, device=caption_ids.device) * float("-inf"), diagonal=1
            )
            out = self.decoder(token_emb, memory, tgt_mask=causal_mask)
            return self.output_proj(out)  # (B, L, vocab_size)
        else:
            # Greedy decoding for inference
            return self._greedy_decode(memory, B)

    def _greedy_decode(self, memory: torch.Tensor, batch_size: int) -> torch.Tensor:
        """Simple greedy decoding for caption generation."""
        device = memory.device
        generated = torch.zeros(batch_size, 1, dtype=torch.long, device=device)  # BOS token
        results = [generated]

        for step in range(self.max_caption_len - 1):
            tokens = torch.cat(results, dim=1)
            token_emb = self.token_embed(tokens)
            pos_ids = torch.arange(tokens.shape[1], device=device)
            token_emb = token_emb + self.pos_embed(pos_ids)

            L = token_emb.shape[1]
            causal_mask = torch.triu(
                torch.ones(L, L, device=device) * float("-inf"), diagonal=1
            )
            out = self.decoder(token_emb, memory, tgt_mask=causal_mask)
            logits = self.output_proj(out[:, -1:])  # (B, 1, vocab)
            next_token = logits.argmax(-1)  # (B, 1)
            results.append(next_token)

        return torch.cat(results, dim=1)  # (B, max_len)


# ─── Pillar 2: Representation Extraction ──────────────────────────────────────

class SemanticFusionEmbedder(nn.Module):
    """
    Fuses multimodal signals (caption text + visual features) into a single
    semantic embedding for downstream recommendation.

    Fusion strategy:
    - Text features: encoded from generated caption via text encoder
    - Visual features: from frozen vision backbone (offline extracted)
    - Fusion: cross-modal attention + element-wise gate

    Output: item semantic embedding of dimension embed_dim
    """

    def __init__(
        self,
        text_dim: int = 768,    # BERT/LLaMA hidden size
        visual_dim: int = 2048,
        embed_dim: int = 256,   # Final item embedding dimension
        nhead: int = 8,
        dropout: float = 0.1,
    ):
        super().__init__()
        d = embed_dim

        self.text_proj = nn.Linear(text_dim, d)
        self.visual_proj = nn.Linear(visual_dim, d)

        # Cross-modal attention: text queries visual
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=d, num_heads=nhead, dropout=dropout, batch_first=True
        )

        # Gating mechanism
        self.gate = nn.Sequential(
            nn.Linear(2 * d, d),
            nn.Sigmoid(),
        )

        # Final projection
        self.output_proj = nn.Sequential(
            nn.Linear(d, d),
            nn.LayerNorm(d),
        )

    def forward(
        self,
        text_features: torch.Tensor,    # (B, text_dim)
        visual_features: torch.Tensor,  # (B, visual_dim)
    ) -> torch.Tensor:
        """Returns: (B, embed_dim) — semantic item embedding."""
        text_proj = self.text_proj(text_features).unsqueeze(1)      # (B, 1, d)
        visual_proj = self.visual_proj(visual_features).unsqueeze(1) # (B, 1, d)

        # Cross-modal attention: text attends to visual
        attn_out, _ = self.cross_attn(
            query=text_proj,
            key=visual_proj,
            value=visual_proj,
        )  # (B, 1, d)

        # Gate fusion
        gate_input = torch.cat([text_proj, attn_out], dim=-1).squeeze(1)  # (B, 2*d)
        gate = self.gate(gate_input)  # (B, d)
        fused = gate * text_proj.squeeze(1) + (1 - gate) * attn_out.squeeze(1)

        return self.output_proj(fused)  # (B, d)


# ─── Pillar 3: Pipeline Integration ───────────────────────────────────────────

class TripartiteRecFramework(nn.Module):
    """
    Full Tripartite Framework for Large-Scale Recommendation.

    Integrates:
    1. ContentInterpreter (offline)
    2. SemanticFusionEmbedder (offline)
    3. Recommendation head (online)

    Online serving:
    - Pre-computed item embeddings from (1) + (2) are stored in vector DB
    - At serving time: encode user query → ANN lookup → rank

    Training objectives:
    - Caption loss: cross-entropy on generated caption tokens
    - Recommendation loss: BPR loss on user-item pairs
    - Alignment loss: cosine similarity between text and visual modalities
    """

    def __init__(
        self,
        visual_dim: int = 2048,
        text_dim: int = 768,
        embed_dim: int = 256,
        caption_vocab_size: int = 32000,
        max_caption_len: int = 64,
    ):
        super().__init__()

        # Pillar 1: Content Interpretation
        self.content_interpreter = ContentInterpreter(
            visual_dim=visual_dim,
            caption_vocab_size=caption_vocab_size,
            d_model=embed_dim,
            max_caption_len=max_caption_len,
        )

        # Pillar 2: Representation Extraction
        self.semantic_embedder = SemanticFusionEmbedder(
            text_dim=text_dim,
            visual_dim=visual_dim,
            embed_dim=embed_dim,
        )

        # User encoder (for recommendation)
        self.user_encoder = nn.Sequential(
            nn.Linear(text_dim, embed_dim),
            nn.LayerNorm(embed_dim),
            nn.GELU(),
            nn.Linear(embed_dim, embed_dim),
        )

    def compute_item_embedding(
        self,
        visual_features: torch.Tensor,  # (B, visual_dim)
        text_features: torch.Tensor,    # (B, text_dim)
        caption_ids: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        """
        Offline: compute item semantic embedding.

        Returns:
          item_embedding: (B, embed_dim)
          caption_logits: (B, L, vocab) if caption_ids provided, else None
        """
        caption_logits = None
        if caption_ids is not None:
            caption_logits = self.content_interpreter(visual_features, caption_ids)

        item_embedding = self.semantic_embedder(text_features, visual_features)
        return item_embedding, caption_logits

    def forward(
        self,
        user_features: torch.Tensor,         # (B, text_dim)
        pos_visual_features: torch.Tensor,   # (B, visual_dim) — positive items
        pos_text_features: torch.Tensor,     # (B, text_dim)
        neg_visual_features: torch.Tensor,   # (B, visual_dim) — negative items
        neg_text_features: torch.Tensor,     # (B, text_dim)
        pos_caption_ids: Optional[torch.Tensor] = None,  # (B, L)
    ) -> Dict[str, torch.Tensor]:
        """
        Full forward pass for training.

        Returns dict with:
          bpr_loss: recommendation BPR loss
          caption_loss: caption generation loss (if pos_caption_ids provided)
          alignment_loss: text-visual alignment loss
          total_loss: weighted sum
        """
        # Compute user embedding
        user_emb = self.user_encoder(user_features)  # (B, embed_dim)

        # Compute positive item embedding
        pos_item_emb, caption_logits = self.compute_item_embedding(
            pos_visual_features, pos_text_features, pos_caption_ids
        )

        # Compute negative item embedding
        neg_item_emb, _ = self.compute_item_embedding(
            neg_visual_features, neg_text_features
        )

        # BPR loss: pos score > neg score
        pos_score = (user_emb * pos_item_emb).sum(dim=-1)  # (B,)
        neg_score = (user_emb * neg_item_emb).sum(dim=-1)  # (B,)
        bpr_loss = -F.logsigmoid(pos_score - neg_score).mean()

        # Caption loss (if labels provided)
        caption_loss = torch.tensor(0.0)
        if caption_logits is not None and pos_caption_ids is not None:
            B, L, V = caption_logits.shape
            caption_loss = F.cross_entropy(
                caption_logits[:, :-1].reshape(-1, V),
                pos_caption_ids[:, 1:].reshape(-1),
                ignore_index=0,
            )

        # Alignment loss: text and visual should be aligned in embedding space
        visual_repr = self.semantic_embedder.visual_proj(pos_visual_features)
        text_repr = self.semantic_embedder.text_proj(pos_text_features)
        alignment_loss = 1.0 - F.cosine_similarity(visual_repr, text_repr, dim=-1).mean()

        total_loss = bpr_loss + 0.5 * caption_loss + 0.1 * alignment_loss

        return {
            "bpr_loss": bpr_loss,
            "caption_loss": caption_loss,
            "alignment_loss": alignment_loss,
            "total_loss": total_loss,
        }
